### PR TITLE
File Structure Organization + Renaming 

### PR DESCRIPTION
**Pull request by ghost**
# HOLY 

This PR is bonkers, but most of the the changes are renaming components and reorganizing files.  Probably the best way to checkout the changes is to actually look at the branch. 

**Comments:**
1. right now this only sets up about half of the structure for the final package. I want to move the Next files into an example starter package, but I am only moving the core files in this PR. 
2. This has changes from #16 and #17 rebased so those should be approved and merged first. I incorporated the changes cuz they seemed wrapped up.

### CODE REVIEW

**Comment by alfonso-paella** [comment]
Can we merge those PRs first lol, so it simplifies a bit the review

**Comment by ghost** [comment]
@alfonso-paella I rebased the branch with `main` (this is how we did it at my old job, is that the right way?) so not the commits are cleaner. Still a lot of files changed.

**Review by alfonso-paella — APPROVED** [review]
In general this looks good to me. However I have never done an npm package before. I wonder if @mPaella can take a look as well as he's got experience with that

**Comment by ghost** [comment]
@alfonso-paella I asked Maxwell @mPaella before creating these changes and made them with his suggestions in mind so I am going to merge them.

**Pull request merged**
